sonar.projectKey=soat-architecture
sonar.projectName=soat-architecture
sonar.sources=.
sonar.exclusions=**/*_test.go,**/mocks/**,vendor/**,bin/**,test/**,docs/**,cmd/seed/**,cmd/create-user/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=test/reports/coverage.out
sonar.sourceEncoding=UTF-8
