// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	query "github.com/muriloperosa/soat-architecture/internal/domain/query"
	mock "github.com/stretchr/testify/mock"

	servico "github.com/muriloperosa/soat-architecture/internal/domain/servico"
)

// ServicoRepository is an autogenerated mock type for the ServicoRepository type
type ServicoRepository struct {
	mock.Mock
}

type ServicoRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ServicoRepository) EXPECT() *ServicoRepository_Expecter {
	return &ServicoRepository_Expecter{mock: &_m.Mock}
}

// Atualizar provides a mock function with given fields: ctx, s
func (_m *ServicoRepository) Atualizar(ctx context.Context, s *servico.Servico) error {
	ret := _m.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for Atualizar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *servico.Servico) error); ok {
		r0 = rf(ctx, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServicoRepository_Atualizar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Atualizar'
type ServicoRepository_Atualizar_Call struct {
	*mock.Call
}

// Atualizar is a helper method to define mock.On call
//   - ctx context.Context
//   - s *servico.Servico
func (_e *ServicoRepository_Expecter) Atualizar(ctx interface{}, s interface{}) *ServicoRepository_Atualizar_Call {
	return &ServicoRepository_Atualizar_Call{Call: _e.mock.On("Atualizar", ctx, s)}
}

func (_c *ServicoRepository_Atualizar_Call) Run(run func(ctx context.Context, s *servico.Servico)) *ServicoRepository_Atualizar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*servico.Servico))
	})
	return _c
}

func (_c *ServicoRepository_Atualizar_Call) Return(_a0 error) *ServicoRepository_Atualizar_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServicoRepository_Atualizar_Call) RunAndReturn(run func(context.Context, *servico.Servico) error) *ServicoRepository_Atualizar_Call {
	_c.Call.Return(run)
	return _c
}

// BuscarPorID provides a mock function with given fields: ctx, id
func (_m *ServicoRepository) BuscarPorID(ctx context.Context, id uint64) (*servico.Servico, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for BuscarPorID")
	}

	var r0 *servico.Servico
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (*servico.Servico, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) *servico.Servico); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*servico.Servico)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ServicoRepository_BuscarPorID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuscarPorID'
type ServicoRepository_BuscarPorID_Call struct {
	*mock.Call
}

// BuscarPorID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *ServicoRepository_Expecter) BuscarPorID(ctx interface{}, id interface{}) *ServicoRepository_BuscarPorID_Call {
	return &ServicoRepository_BuscarPorID_Call{Call: _e.mock.On("BuscarPorID", ctx, id)}
}

func (_c *ServicoRepository_BuscarPorID_Call) Run(run func(ctx context.Context, id uint64)) *ServicoRepository_BuscarPorID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *ServicoRepository_BuscarPorID_Call) Return(_a0 *servico.Servico, _a1 error) *ServicoRepository_BuscarPorID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ServicoRepository_BuscarPorID_Call) RunAndReturn(run func(context.Context, uint64) (*servico.Servico, error)) *ServicoRepository_BuscarPorID_Call {
	_c.Call.Return(run)
	return _c
}

// Listar provides a mock function with given fields: ctx, params
func (_m *ServicoRepository) Listar(ctx context.Context, params query.Params) (query.Page[*servico.Servico], error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Listar")
	}

	var r0 query.Page[*servico.Servico]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, query.Params) (query.Page[*servico.Servico], error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, query.Params) query.Page[*servico.Servico]); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(query.Page[*servico.Servico])
	}

	if rf, ok := ret.Get(1).(func(context.Context, query.Params) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ServicoRepository_Listar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Listar'
type ServicoRepository_Listar_Call struct {
	*mock.Call
}

// Listar is a helper method to define mock.On call
//   - ctx context.Context
//   - params query.Params
func (_e *ServicoRepository_Expecter) Listar(ctx interface{}, params interface{}) *ServicoRepository_Listar_Call {
	return &ServicoRepository_Listar_Call{Call: _e.mock.On("Listar", ctx, params)}
}

func (_c *ServicoRepository_Listar_Call) Run(run func(ctx context.Context, params query.Params)) *ServicoRepository_Listar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(query.Params))
	})
	return _c
}

func (_c *ServicoRepository_Listar_Call) Return(_a0 query.Page[*servico.Servico], _a1 error) *ServicoRepository_Listar_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ServicoRepository_Listar_Call) RunAndReturn(run func(context.Context, query.Params) (query.Page[*servico.Servico], error)) *ServicoRepository_Listar_Call {
	_c.Call.Return(run)
	return _c
}

// Salvar provides a mock function with given fields: ctx, s
func (_m *ServicoRepository) Salvar(ctx context.Context, s *servico.Servico) error {
	ret := _m.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for Salvar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *servico.Servico) error); ok {
		r0 = rf(ctx, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServicoRepository_Salvar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Salvar'
type ServicoRepository_Salvar_Call struct {
	*mock.Call
}

// Salvar is a helper method to define mock.On call
//   - ctx context.Context
//   - s *servico.Servico
func (_e *ServicoRepository_Expecter) Salvar(ctx interface{}, s interface{}) *ServicoRepository_Salvar_Call {
	return &ServicoRepository_Salvar_Call{Call: _e.mock.On("Salvar", ctx, s)}
}

func (_c *ServicoRepository_Salvar_Call) Run(run func(ctx context.Context, s *servico.Servico)) *ServicoRepository_Salvar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*servico.Servico))
	})
	return _c
}

func (_c *ServicoRepository_Salvar_Call) Return(_a0 error) *ServicoRepository_Salvar_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServicoRepository_Salvar_Call) RunAndReturn(run func(context.Context, *servico.Servico) error) *ServicoRepository_Salvar_Call {
	_c.Call.Return(run)
	return _c
}

// NewServicoRepository creates a new instance of ServicoRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServicoRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServicoRepository {
	mock := &ServicoRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
