// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	reservapeca "github.com/muriloperosa/soat-architecture/internal/domain/reservapeca"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// Atualizar provides a mock function with given fields: ctx, _a1
func (_m *Repository) Atualizar(ctx context.Context, _a1 *reservapeca.ReservaPeca) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Atualizar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *reservapeca.ReservaPeca) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_Atualizar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Atualizar'
type Repository_Atualizar_Call struct {
	*mock.Call
}

// Atualizar is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *reservapeca.ReservaPeca
func (_e *Repository_Expecter) Atualizar(ctx interface{}, _a1 interface{}) *Repository_Atualizar_Call {
	return &Repository_Atualizar_Call{Call: _e.mock.On("Atualizar", ctx, _a1)}
}

func (_c *Repository_Atualizar_Call) Run(run func(ctx context.Context, _a1 *reservapeca.ReservaPeca)) *Repository_Atualizar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*reservapeca.ReservaPeca))
	})
	return _c
}

func (_c *Repository_Atualizar_Call) Return(_a0 error) *Repository_Atualizar_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_Atualizar_Call) RunAndReturn(run func(context.Context, *reservapeca.ReservaPeca) error) *Repository_Atualizar_Call {
	_c.Call.Return(run)
	return _c
}

// BuscarPorOrdemEPeca provides a mock function with given fields: ctx, ordemServicoID, pecaID
func (_m *Repository) BuscarPorOrdemEPeca(ctx context.Context, ordemServicoID uint64, pecaID uint64) (*reservapeca.ReservaPeca, error) {
	ret := _m.Called(ctx, ordemServicoID, pecaID)

	if len(ret) == 0 {
		panic("no return value specified for BuscarPorOrdemEPeca")
	}

	var r0 *reservapeca.ReservaPeca
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) (*reservapeca.ReservaPeca, error)); ok {
		return rf(ctx, ordemServicoID, pecaID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) *reservapeca.ReservaPeca); ok {
		r0 = rf(ctx, ordemServicoID, pecaID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reservapeca.ReservaPeca)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, uint64) error); ok {
		r1 = rf(ctx, ordemServicoID, pecaID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_BuscarPorOrdemEPeca_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuscarPorOrdemEPeca'
type Repository_BuscarPorOrdemEPeca_Call struct {
	*mock.Call
}

// BuscarPorOrdemEPeca is a helper method to define mock.On call
//   - ctx context.Context
//   - ordemServicoID uint64
//   - pecaID uint64
func (_e *Repository_Expecter) BuscarPorOrdemEPeca(ctx interface{}, ordemServicoID interface{}, pecaID interface{}) *Repository_BuscarPorOrdemEPeca_Call {
	return &Repository_BuscarPorOrdemEPeca_Call{Call: _e.mock.On("BuscarPorOrdemEPeca", ctx, ordemServicoID, pecaID)}
}

func (_c *Repository_BuscarPorOrdemEPeca_Call) Run(run func(ctx context.Context, ordemServicoID uint64, pecaID uint64)) *Repository_BuscarPorOrdemEPeca_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(uint64))
	})
	return _c
}

func (_c *Repository_BuscarPorOrdemEPeca_Call) Return(_a0 *reservapeca.ReservaPeca, _a1 error) *Repository_BuscarPorOrdemEPeca_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_BuscarPorOrdemEPeca_Call) RunAndReturn(run func(context.Context, uint64, uint64) (*reservapeca.ReservaPeca, error)) *Repository_BuscarPorOrdemEPeca_Call {
	_c.Call.Return(run)
	return _c
}

// BuscarPorOrdemServico provides a mock function with given fields: ctx, ordemServicoID
func (_m *Repository) BuscarPorOrdemServico(ctx context.Context, ordemServicoID uint64) ([]*reservapeca.ReservaPeca, error) {
	ret := _m.Called(ctx, ordemServicoID)

	if len(ret) == 0 {
		panic("no return value specified for BuscarPorOrdemServico")
	}

	var r0 []*reservapeca.ReservaPeca
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) ([]*reservapeca.ReservaPeca, error)); ok {
		return rf(ctx, ordemServicoID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) []*reservapeca.ReservaPeca); ok {
		r0 = rf(ctx, ordemServicoID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*reservapeca.ReservaPeca)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, ordemServicoID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_BuscarPorOrdemServico_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuscarPorOrdemServico'
type Repository_BuscarPorOrdemServico_Call struct {
	*mock.Call
}

// BuscarPorOrdemServico is a helper method to define mock.On call
//   - ctx context.Context
//   - ordemServicoID uint64
func (_e *Repository_Expecter) BuscarPorOrdemServico(ctx interface{}, ordemServicoID interface{}) *Repository_BuscarPorOrdemServico_Call {
	return &Repository_BuscarPorOrdemServico_Call{Call: _e.mock.On("BuscarPorOrdemServico", ctx, ordemServicoID)}
}

func (_c *Repository_BuscarPorOrdemServico_Call) Run(run func(ctx context.Context, ordemServicoID uint64)) *Repository_BuscarPorOrdemServico_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *Repository_BuscarPorOrdemServico_Call) Return(_a0 []*reservapeca.ReservaPeca, _a1 error) *Repository_BuscarPorOrdemServico_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_BuscarPorOrdemServico_Call) RunAndReturn(run func(context.Context, uint64) ([]*reservapeca.ReservaPeca, error)) *Repository_BuscarPorOrdemServico_Call {
	_c.Call.Return(run)
	return _c
}

// Remover provides a mock function with given fields: ctx, ordemServicoID, pecaID
func (_m *Repository) Remover(ctx context.Context, ordemServicoID uint64, pecaID uint64) error {
	ret := _m.Called(ctx, ordemServicoID, pecaID)

	if len(ret) == 0 {
		panic("no return value specified for Remover")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) error); ok {
		r0 = rf(ctx, ordemServicoID, pecaID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_Remover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remover'
type Repository_Remover_Call struct {
	*mock.Call
}

// Remover is a helper method to define mock.On call
//   - ctx context.Context
//   - ordemServicoID uint64
//   - pecaID uint64
func (_e *Repository_Expecter) Remover(ctx interface{}, ordemServicoID interface{}, pecaID interface{}) *Repository_Remover_Call {
	return &Repository_Remover_Call{Call: _e.mock.On("Remover", ctx, ordemServicoID, pecaID)}
}

func (_c *Repository_Remover_Call) Run(run func(ctx context.Context, ordemServicoID uint64, pecaID uint64)) *Repository_Remover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(uint64))
	})
	return _c
}

func (_c *Repository_Remover_Call) Return(_a0 error) *Repository_Remover_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_Remover_Call) RunAndReturn(run func(context.Context, uint64, uint64) error) *Repository_Remover_Call {
	_c.Call.Return(run)
	return _c
}

// Salvar provides a mock function with given fields: ctx, _a1
func (_m *Repository) Salvar(ctx context.Context, _a1 *reservapeca.ReservaPeca) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Salvar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *reservapeca.ReservaPeca) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_Salvar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Salvar'
type Repository_Salvar_Call struct {
	*mock.Call
}

// Salvar is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *reservapeca.ReservaPeca
func (_e *Repository_Expecter) Salvar(ctx interface{}, _a1 interface{}) *Repository_Salvar_Call {
	return &Repository_Salvar_Call{Call: _e.mock.On("Salvar", ctx, _a1)}
}

func (_c *Repository_Salvar_Call) Run(run func(ctx context.Context, _a1 *reservapeca.ReservaPeca)) *Repository_Salvar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*reservapeca.ReservaPeca))
	})
	return _c
}

func (_c *Repository_Salvar_Call) Return(_a0 error) *Repository_Salvar_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_Salvar_Call) RunAndReturn(run func(context.Context, *reservapeca.ReservaPeca) error) *Repository_Salvar_Call {
	_c.Call.Return(run)
	return _c
}

// SomarQuantidadeReservada provides a mock function with given fields: ctx, pecaID
func (_m *Repository) SomarQuantidadeReservada(ctx context.Context, pecaID uint64) (int, error) {
	ret := _m.Called(ctx, pecaID)

	if len(ret) == 0 {
		panic("no return value specified for SomarQuantidadeReservada")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (int, error)); ok {
		return rf(ctx, pecaID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) int); ok {
		r0 = rf(ctx, pecaID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, pecaID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_SomarQuantidadeReservada_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SomarQuantidadeReservada'
type Repository_SomarQuantidadeReservada_Call struct {
	*mock.Call
}

// SomarQuantidadeReservada is a helper method to define mock.On call
//   - ctx context.Context
//   - pecaID uint64
func (_e *Repository_Expecter) SomarQuantidadeReservada(ctx interface{}, pecaID interface{}) *Repository_SomarQuantidadeReservada_Call {
	return &Repository_SomarQuantidadeReservada_Call{Call: _e.mock.On("SomarQuantidadeReservada", ctx, pecaID)}
}

func (_c *Repository_SomarQuantidadeReservada_Call) Run(run func(ctx context.Context, pecaID uint64)) *Repository_SomarQuantidadeReservada_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *Repository_SomarQuantidadeReservada_Call) Return(_a0 int, _a1 error) *Repository_SomarQuantidadeReservada_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_SomarQuantidadeReservada_Call) RunAndReturn(run func(context.Context, uint64) (int, error)) *Repository_SomarQuantidadeReservada_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
