// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	relatorio "github.com/muriloperosa/soat-architecture/internal/domain/relatorio"
	mock "github.com/stretchr/testify/mock"
)

// RelatorioTransicaoStatusRepository is an autogenerated mock type for the RelatorioTransicaoStatusRepository type
type RelatorioTransicaoStatusRepository struct {
	mock.Mock
}

type RelatorioTransicaoStatusRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *RelatorioTransicaoStatusRepository) EXPECT() *RelatorioTransicaoStatusRepository_Expecter {
	return &RelatorioTransicaoStatusRepository_Expecter{mock: &_m.Mock}
}

// CalcularTransicaoStatus provides a mock function with given fields: ctx, params
func (_m *RelatorioTransicaoStatusRepository) CalcularTransicaoStatus(ctx context.Context, params relatorio.CalcularTransicaoStatusParams) (relatorio.TransicaoStatusResultado, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CalcularTransicaoStatus")
	}

	var r0 relatorio.TransicaoStatusResultado
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, relatorio.CalcularTransicaoStatusParams) (relatorio.TransicaoStatusResultado, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, relatorio.CalcularTransicaoStatusParams) relatorio.TransicaoStatusResultado); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(relatorio.TransicaoStatusResultado)
	}

	if rf, ok := ret.Get(1).(func(context.Context, relatorio.CalcularTransicaoStatusParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RelatorioTransicaoStatusRepository_CalcularTransicaoStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CalcularTransicaoStatus'
type RelatorioTransicaoStatusRepository_CalcularTransicaoStatus_Call struct {
	*mock.Call
}

// CalcularTransicaoStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - params relatorio.CalcularTransicaoStatusParams
func (_e *RelatorioTransicaoStatusRepository_Expecter) CalcularTransicaoStatus(ctx interface{}, params interface{}) *RelatorioTransicaoStatusRepository_CalcularTransicaoStatus_Call {
	return &RelatorioTransicaoStatusRepository_CalcularTransicaoStatus_Call{Call: _e.mock.On("CalcularTransicaoStatus", ctx, params)}
}

func (_c *RelatorioTransicaoStatusRepository_CalcularTransicaoStatus_Call) Run(run func(ctx context.Context, params relatorio.CalcularTransicaoStatusParams)) *RelatorioTransicaoStatusRepository_CalcularTransicaoStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(relatorio.CalcularTransicaoStatusParams))
	})
	return _c
}

func (_c *RelatorioTransicaoStatusRepository_CalcularTransicaoStatus_Call) Return(_a0 relatorio.TransicaoStatusResultado, _a1 error) *RelatorioTransicaoStatusRepository_CalcularTransicaoStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RelatorioTransicaoStatusRepository_CalcularTransicaoStatus_Call) RunAndReturn(run func(context.Context, relatorio.CalcularTransicaoStatusParams) (relatorio.TransicaoStatusResultado, error)) *RelatorioTransicaoStatusRepository_CalcularTransicaoStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewRelatorioTransicaoStatusRepository creates a new instance of RelatorioTransicaoStatusRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRelatorioTransicaoStatusRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RelatorioTransicaoStatusRepository {
	mock := &RelatorioTransicaoStatusRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
