// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	ordemservico "github.com/muriloperosa/soat-architecture/internal/domain/ordemservico"
	mock "github.com/stretchr/testify/mock"
)

// OrdemServicoRepository is an autogenerated mock type for the OrdemServicoRepository type
type OrdemServicoRepository struct {
	mock.Mock
}

type OrdemServicoRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *OrdemServicoRepository) EXPECT() *OrdemServicoRepository_Expecter {
	return &OrdemServicoRepository_Expecter{mock: &_m.Mock}
}

// Atualizar provides a mock function with given fields: ctx, ordemServico
func (_m *OrdemServicoRepository) Atualizar(ctx context.Context, ordemServico *ordemservico.OrdemServico) error {
	ret := _m.Called(ctx, ordemServico)

	if len(ret) == 0 {
		panic("no return value specified for Atualizar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ordemservico.OrdemServico) error); ok {
		r0 = rf(ctx, ordemServico)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrdemServicoRepository_Atualizar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Atualizar'
type OrdemServicoRepository_Atualizar_Call struct {
	*mock.Call
}

// Atualizar is a helper method to define mock.On call
//   - ctx context.Context
//   - ordemServico *ordemservico.OrdemServico
func (_e *OrdemServicoRepository_Expecter) Atualizar(ctx interface{}, ordemServico interface{}) *OrdemServicoRepository_Atualizar_Call {
	return &OrdemServicoRepository_Atualizar_Call{Call: _e.mock.On("Atualizar", ctx, ordemServico)}
}

func (_c *OrdemServicoRepository_Atualizar_Call) Run(run func(ctx context.Context, ordemServico *ordemservico.OrdemServico)) *OrdemServicoRepository_Atualizar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*ordemservico.OrdemServico))
	})
	return _c
}

func (_c *OrdemServicoRepository_Atualizar_Call) Return(_a0 error) *OrdemServicoRepository_Atualizar_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrdemServicoRepository_Atualizar_Call) RunAndReturn(run func(context.Context, *ordemservico.OrdemServico) error) *OrdemServicoRepository_Atualizar_Call {
	_c.Call.Return(run)
	return _c
}

// BuscarPorID provides a mock function with given fields: ctx, id
func (_m *OrdemServicoRepository) BuscarPorID(ctx context.Context, id uint64) (*ordemservico.OrdemServico, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for BuscarPorID")
	}

	var r0 *ordemservico.OrdemServico
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (*ordemservico.OrdemServico, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) *ordemservico.OrdemServico); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ordemservico.OrdemServico)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrdemServicoRepository_BuscarPorID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuscarPorID'
type OrdemServicoRepository_BuscarPorID_Call struct {
	*mock.Call
}

// BuscarPorID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *OrdemServicoRepository_Expecter) BuscarPorID(ctx interface{}, id interface{}) *OrdemServicoRepository_BuscarPorID_Call {
	return &OrdemServicoRepository_BuscarPorID_Call{Call: _e.mock.On("BuscarPorID", ctx, id)}
}

func (_c *OrdemServicoRepository_BuscarPorID_Call) Run(run func(ctx context.Context, id uint64)) *OrdemServicoRepository_BuscarPorID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *OrdemServicoRepository_BuscarPorID_Call) Return(_a0 *ordemservico.OrdemServico, _a1 error) *OrdemServicoRepository_BuscarPorID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrdemServicoRepository_BuscarPorID_Call) RunAndReturn(run func(context.Context, uint64) (*ordemservico.OrdemServico, error)) *OrdemServicoRepository_BuscarPorID_Call {
	_c.Call.Return(run)
	return _c
}

// BuscarPorNumero provides a mock function with given fields: ctx, numero
func (_m *OrdemServicoRepository) BuscarPorNumero(ctx context.Context, numero string) (*ordemservico.OrdemServico, error) {
	ret := _m.Called(ctx, numero)

	if len(ret) == 0 {
		panic("no return value specified for BuscarPorNumero")
	}

	var r0 *ordemservico.OrdemServico
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*ordemservico.OrdemServico, error)); ok {
		return rf(ctx, numero)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *ordemservico.OrdemServico); ok {
		r0 = rf(ctx, numero)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ordemservico.OrdemServico)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, numero)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrdemServicoRepository_BuscarPorNumero_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuscarPorNumero'
type OrdemServicoRepository_BuscarPorNumero_Call struct {
	*mock.Call
}

// BuscarPorNumero is a helper method to define mock.On call
//   - ctx context.Context
//   - numero string
func (_e *OrdemServicoRepository_Expecter) BuscarPorNumero(ctx interface{}, numero interface{}) *OrdemServicoRepository_BuscarPorNumero_Call {
	return &OrdemServicoRepository_BuscarPorNumero_Call{Call: _e.mock.On("BuscarPorNumero", ctx, numero)}
}

func (_c *OrdemServicoRepository_BuscarPorNumero_Call) Run(run func(ctx context.Context, numero string)) *OrdemServicoRepository_BuscarPorNumero_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrdemServicoRepository_BuscarPorNumero_Call) Return(_a0 *ordemservico.OrdemServico, _a1 error) *OrdemServicoRepository_BuscarPorNumero_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrdemServicoRepository_BuscarPorNumero_Call) RunAndReturn(run func(context.Context, string) (*ordemservico.OrdemServico, error)) *OrdemServicoRepository_BuscarPorNumero_Call {
	_c.Call.Return(run)
	return _c
}

// Salvar provides a mock function with given fields: ctx, ordemServico
func (_m *OrdemServicoRepository) Salvar(ctx context.Context, ordemServico *ordemservico.OrdemServico) error {
	ret := _m.Called(ctx, ordemServico)

	if len(ret) == 0 {
		panic("no return value specified for Salvar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ordemservico.OrdemServico) error); ok {
		r0 = rf(ctx, ordemServico)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrdemServicoRepository_Salvar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Salvar'
type OrdemServicoRepository_Salvar_Call struct {
	*mock.Call
}

// Salvar is a helper method to define mock.On call
//   - ctx context.Context
//   - ordemServico *ordemservico.OrdemServico
func (_e *OrdemServicoRepository_Expecter) Salvar(ctx interface{}, ordemServico interface{}) *OrdemServicoRepository_Salvar_Call {
	return &OrdemServicoRepository_Salvar_Call{Call: _e.mock.On("Salvar", ctx, ordemServico)}
}

func (_c *OrdemServicoRepository_Salvar_Call) Run(run func(ctx context.Context, ordemServico *ordemservico.OrdemServico)) *OrdemServicoRepository_Salvar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*ordemservico.OrdemServico))
	})
	return _c
}

func (_c *OrdemServicoRepository_Salvar_Call) Return(_a0 error) *OrdemServicoRepository_Salvar_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrdemServicoRepository_Salvar_Call) RunAndReturn(run func(context.Context, *ordemservico.OrdemServico) error) *OrdemServicoRepository_Salvar_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrdemServicoRepository creates a new instance of OrdemServicoRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrdemServicoRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrdemServicoRepository {
	mock := &OrdemServicoRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
