// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	auth "github.com/muriloperosa/soat-architecture/internal/domain/auth"

	mock "github.com/stretchr/testify/mock"
)

// CredenciaisRepository is an autogenerated mock type for the CredenciaisRepository type
type CredenciaisRepository struct {
	mock.Mock
}

type CredenciaisRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CredenciaisRepository) EXPECT() *CredenciaisRepository_Expecter {
	return &CredenciaisRepository_Expecter{mock: &_m.Mock}
}

// BuscarPorEmail provides a mock function with given fields: ctx, email
func (_m *CredenciaisRepository) BuscarPorEmail(ctx context.Context, email string) (*auth.Credencial, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for BuscarPorEmail")
	}

	var r0 *auth.Credencial
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*auth.Credencial, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *auth.Credencial); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.Credencial)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CredenciaisRepository_BuscarPorEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuscarPorEmail'
type CredenciaisRepository_BuscarPorEmail_Call struct {
	*mock.Call
}

// BuscarPorEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *CredenciaisRepository_Expecter) BuscarPorEmail(ctx interface{}, email interface{}) *CredenciaisRepository_BuscarPorEmail_Call {
	return &CredenciaisRepository_BuscarPorEmail_Call{Call: _e.mock.On("BuscarPorEmail", ctx, email)}
}

func (_c *CredenciaisRepository_BuscarPorEmail_Call) Run(run func(ctx context.Context, email string)) *CredenciaisRepository_BuscarPorEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CredenciaisRepository_BuscarPorEmail_Call) Return(_a0 *auth.Credencial, _a1 error) *CredenciaisRepository_BuscarPorEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CredenciaisRepository_BuscarPorEmail_Call) RunAndReturn(run func(context.Context, string) (*auth.Credencial, error)) *CredenciaisRepository_BuscarPorEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewCredenciaisRepository creates a new instance of CredenciaisRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCredenciaisRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CredenciaisRepository {
	mock := &CredenciaisRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
