// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	auth "github.com/muriloperosa/soat-architecture/internal/domain/auth"
	mock "github.com/stretchr/testify/mock"
)

// JWTProvider is an autogenerated mock type for the JWTProvider type
type JWTProvider struct {
	mock.Mock
}

type JWTProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *JWTProvider) EXPECT() *JWTProvider_Expecter {
	return &JWTProvider_Expecter{mock: &_m.Mock}
}

// GerarAccessToken provides a mock function with given fields: subject, tipo, papel
func (_m *JWTProvider) GerarAccessToken(subject string, tipo auth.TipoUsuario, papel auth.PapelUsuario) (string, error) {
	ret := _m.Called(subject, tipo, papel)

	if len(ret) == 0 {
		panic("no return value specified for GerarAccessToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, auth.TipoUsuario, auth.PapelUsuario) (string, error)); ok {
		return rf(subject, tipo, papel)
	}
	if rf, ok := ret.Get(0).(func(string, auth.TipoUsuario, auth.PapelUsuario) string); ok {
		r0 = rf(subject, tipo, papel)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, auth.TipoUsuario, auth.PapelUsuario) error); ok {
		r1 = rf(subject, tipo, papel)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// JWTProvider_GerarAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GerarAccessToken'
type JWTProvider_GerarAccessToken_Call struct {
	*mock.Call
}

// GerarAccessToken is a helper method to define mock.On call
//   - subject string
//   - tipo auth.TipoUsuario
//   - papel auth.PapelUsuario
func (_e *JWTProvider_Expecter) GerarAccessToken(subject interface{}, tipo interface{}, papel interface{}) *JWTProvider_GerarAccessToken_Call {
	return &JWTProvider_GerarAccessToken_Call{Call: _e.mock.On("GerarAccessToken", subject, tipo, papel)}
}

func (_c *JWTProvider_GerarAccessToken_Call) Run(run func(subject string, tipo auth.TipoUsuario, papel auth.PapelUsuario)) *JWTProvider_GerarAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(auth.TipoUsuario), args[2].(auth.PapelUsuario))
	})
	return _c
}

func (_c *JWTProvider_GerarAccessToken_Call) Return(_a0 string, _a1 error) *JWTProvider_GerarAccessToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *JWTProvider_GerarAccessToken_Call) RunAndReturn(run func(string, auth.TipoUsuario, auth.PapelUsuario) (string, error)) *JWTProvider_GerarAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// GerarRefreshTokenBruto provides a mock function with no fields
func (_m *JWTProvider) GerarRefreshTokenBruto() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GerarRefreshTokenBruto")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// JWTProvider_GerarRefreshTokenBruto_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GerarRefreshTokenBruto'
type JWTProvider_GerarRefreshTokenBruto_Call struct {
	*mock.Call
}

// GerarRefreshTokenBruto is a helper method to define mock.On call
func (_e *JWTProvider_Expecter) GerarRefreshTokenBruto() *JWTProvider_GerarRefreshTokenBruto_Call {
	return &JWTProvider_GerarRefreshTokenBruto_Call{Call: _e.mock.On("GerarRefreshTokenBruto")}
}

func (_c *JWTProvider_GerarRefreshTokenBruto_Call) Run(run func()) *JWTProvider_GerarRefreshTokenBruto_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *JWTProvider_GerarRefreshTokenBruto_Call) Return(_a0 string, _a1 error) *JWTProvider_GerarRefreshTokenBruto_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *JWTProvider_GerarRefreshTokenBruto_Call) RunAndReturn(run func() (string, error)) *JWTProvider_GerarRefreshTokenBruto_Call {
	_c.Call.Return(run)
	return _c
}

// NewJWTProvider creates a new instance of JWTProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJWTProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *JWTProvider {
	mock := &JWTProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
