// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	auth "github.com/muriloperosa/soat-architecture/internal/domain/auth"

	mock "github.com/stretchr/testify/mock"
)

// RefreshTokenRepository is an autogenerated mock type for the RefreshTokenRepository type
type RefreshTokenRepository struct {
	mock.Mock
}

type RefreshTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *RefreshTokenRepository) EXPECT() *RefreshTokenRepository_Expecter {
	return &RefreshTokenRepository_Expecter{mock: &_m.Mock}
}

// AccessTokenRevogado provides a mock function with given fields: ctx, jti
func (_m *RefreshTokenRepository) AccessTokenRevogado(ctx context.Context, jti string) (bool, error) {
	ret := _m.Called(ctx, jti)

	if len(ret) == 0 {
		panic("no return value specified for AccessTokenRevogado")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, jti)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, jti)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, jti)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RefreshTokenRepository_AccessTokenRevogado_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AccessTokenRevogado'
type RefreshTokenRepository_AccessTokenRevogado_Call struct {
	*mock.Call
}

// AccessTokenRevogado is a helper method to define mock.On call
//   - ctx context.Context
//   - jti string
func (_e *RefreshTokenRepository_Expecter) AccessTokenRevogado(ctx interface{}, jti interface{}) *RefreshTokenRepository_AccessTokenRevogado_Call {
	return &RefreshTokenRepository_AccessTokenRevogado_Call{Call: _e.mock.On("AccessTokenRevogado", ctx, jti)}
}

func (_c *RefreshTokenRepository_AccessTokenRevogado_Call) Run(run func(ctx context.Context, jti string)) *RefreshTokenRepository_AccessTokenRevogado_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RefreshTokenRepository_AccessTokenRevogado_Call) Return(_a0 bool, _a1 error) *RefreshTokenRepository_AccessTokenRevogado_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RefreshTokenRepository_AccessTokenRevogado_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *RefreshTokenRepository_AccessTokenRevogado_Call {
	_c.Call.Return(run)
	return _c
}

// BuscarPorHash provides a mock function with given fields: ctx, tokenHash
func (_m *RefreshTokenRepository) BuscarPorHash(ctx context.Context, tokenHash string) (*auth.RefreshToken, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for BuscarPorHash")
	}

	var r0 *auth.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*auth.RefreshToken, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *auth.RefreshToken); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.RefreshToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RefreshTokenRepository_BuscarPorHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuscarPorHash'
type RefreshTokenRepository_BuscarPorHash_Call struct {
	*mock.Call
}

// BuscarPorHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *RefreshTokenRepository_Expecter) BuscarPorHash(ctx interface{}, tokenHash interface{}) *RefreshTokenRepository_BuscarPorHash_Call {
	return &RefreshTokenRepository_BuscarPorHash_Call{Call: _e.mock.On("BuscarPorHash", ctx, tokenHash)}
}

func (_c *RefreshTokenRepository_BuscarPorHash_Call) Run(run func(ctx context.Context, tokenHash string)) *RefreshTokenRepository_BuscarPorHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RefreshTokenRepository_BuscarPorHash_Call) Return(_a0 *auth.RefreshToken, _a1 error) *RefreshTokenRepository_BuscarPorHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RefreshTokenRepository_BuscarPorHash_Call) RunAndReturn(run func(context.Context, string) (*auth.RefreshToken, error)) *RefreshTokenRepository_BuscarPorHash_Call {
	_c.Call.Return(run)
	return _c
}

// Revogar provides a mock function with given fields: ctx, id
func (_m *RefreshTokenRepository) Revogar(ctx context.Context, id uint64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Revogar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RefreshTokenRepository_Revogar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revogar'
type RefreshTokenRepository_Revogar_Call struct {
	*mock.Call
}

// Revogar is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *RefreshTokenRepository_Expecter) Revogar(ctx interface{}, id interface{}) *RefreshTokenRepository_Revogar_Call {
	return &RefreshTokenRepository_Revogar_Call{Call: _e.mock.On("Revogar", ctx, id)}
}

func (_c *RefreshTokenRepository_Revogar_Call) Run(run func(ctx context.Context, id uint64)) *RefreshTokenRepository_Revogar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *RefreshTokenRepository_Revogar_Call) Return(_a0 error) *RefreshTokenRepository_Revogar_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RefreshTokenRepository_Revogar_Call) RunAndReturn(run func(context.Context, uint64) error) *RefreshTokenRepository_Revogar_Call {
	_c.Call.Return(run)
	return _c
}

// Salvar provides a mock function with given fields: ctx, rt
func (_m *RefreshTokenRepository) Salvar(ctx context.Context, rt *auth.RefreshToken) error {
	ret := _m.Called(ctx, rt)

	if len(ret) == 0 {
		panic("no return value specified for Salvar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *auth.RefreshToken) error); ok {
		r0 = rf(ctx, rt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RefreshTokenRepository_Salvar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Salvar'
type RefreshTokenRepository_Salvar_Call struct {
	*mock.Call
}

// Salvar is a helper method to define mock.On call
//   - ctx context.Context
//   - rt *auth.RefreshToken
func (_e *RefreshTokenRepository_Expecter) Salvar(ctx interface{}, rt interface{}) *RefreshTokenRepository_Salvar_Call {
	return &RefreshTokenRepository_Salvar_Call{Call: _e.mock.On("Salvar", ctx, rt)}
}

func (_c *RefreshTokenRepository_Salvar_Call) Run(run func(ctx context.Context, rt *auth.RefreshToken)) *RefreshTokenRepository_Salvar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*auth.RefreshToken))
	})
	return _c
}

func (_c *RefreshTokenRepository_Salvar_Call) Return(_a0 error) *RefreshTokenRepository_Salvar_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RefreshTokenRepository_Salvar_Call) RunAndReturn(run func(context.Context, *auth.RefreshToken) error) *RefreshTokenRepository_Salvar_Call {
	_c.Call.Return(run)
	return _c
}

// NewRefreshTokenRepository creates a new instance of RefreshTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRefreshTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RefreshTokenRepository {
	mock := &RefreshTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
