// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	auth "github.com/muriloperosa/soat-architecture/internal/domain/auth"

	mock "github.com/stretchr/testify/mock"
)

// RepositorioRefreshToken is an autogenerated mock type for the RepositorioRefreshToken type
type RepositorioRefreshToken struct {
	mock.Mock
}

type RepositorioRefreshToken_Expecter struct {
	mock *mock.Mock
}

func (_m *RepositorioRefreshToken) EXPECT() *RepositorioRefreshToken_Expecter {
	return &RepositorioRefreshToken_Expecter{mock: &_m.Mock}
}

// BuscarPorHash provides a mock function with given fields: ctx, tokenHash
func (_m *RepositorioRefreshToken) BuscarPorHash(ctx context.Context, tokenHash string) (*auth.RefreshToken, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for BuscarPorHash")
	}

	var r0 *auth.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*auth.RefreshToken, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *auth.RefreshToken); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.RefreshToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositorioRefreshToken_BuscarPorHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuscarPorHash'
type RepositorioRefreshToken_BuscarPorHash_Call struct {
	*mock.Call
}

// BuscarPorHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *RepositorioRefreshToken_Expecter) BuscarPorHash(ctx interface{}, tokenHash interface{}) *RepositorioRefreshToken_BuscarPorHash_Call {
	return &RepositorioRefreshToken_BuscarPorHash_Call{Call: _e.mock.On("BuscarPorHash", ctx, tokenHash)}
}

func (_c *RepositorioRefreshToken_BuscarPorHash_Call) Run(run func(ctx context.Context, tokenHash string)) *RepositorioRefreshToken_BuscarPorHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RepositorioRefreshToken_BuscarPorHash_Call) Return(_a0 *auth.RefreshToken, _a1 error) *RepositorioRefreshToken_BuscarPorHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositorioRefreshToken_BuscarPorHash_Call) RunAndReturn(run func(context.Context, string) (*auth.RefreshToken, error)) *RepositorioRefreshToken_BuscarPorHash_Call {
	_c.Call.Return(run)
	return _c
}

// Revogar provides a mock function with given fields: ctx, id
func (_m *RepositorioRefreshToken) Revogar(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Revogar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RepositorioRefreshToken_Revogar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revogar'
type RepositorioRefreshToken_Revogar_Call struct {
	*mock.Call
}

// Revogar is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *RepositorioRefreshToken_Expecter) Revogar(ctx interface{}, id interface{}) *RepositorioRefreshToken_Revogar_Call {
	return &RepositorioRefreshToken_Revogar_Call{Call: _e.mock.On("Revogar", ctx, id)}
}

func (_c *RepositorioRefreshToken_Revogar_Call) Run(run func(ctx context.Context, id string)) *RepositorioRefreshToken_Revogar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RepositorioRefreshToken_Revogar_Call) Return(_a0 error) *RepositorioRefreshToken_Revogar_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RepositorioRefreshToken_Revogar_Call) RunAndReturn(run func(context.Context, string) error) *RepositorioRefreshToken_Revogar_Call {
	_c.Call.Return(run)
	return _c
}

// Salvar provides a mock function with given fields: ctx, rt
func (_m *RepositorioRefreshToken) Salvar(ctx context.Context, rt *auth.RefreshToken) error {
	ret := _m.Called(ctx, rt)

	if len(ret) == 0 {
		panic("no return value specified for Salvar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *auth.RefreshToken) error); ok {
		r0 = rf(ctx, rt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RepositorioRefreshToken_Salvar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Salvar'
type RepositorioRefreshToken_Salvar_Call struct {
	*mock.Call
}

// Salvar is a helper method to define mock.On call
//   - ctx context.Context
//   - rt *auth.RefreshToken
func (_e *RepositorioRefreshToken_Expecter) Salvar(ctx interface{}, rt interface{}) *RepositorioRefreshToken_Salvar_Call {
	return &RepositorioRefreshToken_Salvar_Call{Call: _e.mock.On("Salvar", ctx, rt)}
}

func (_c *RepositorioRefreshToken_Salvar_Call) Run(run func(ctx context.Context, rt *auth.RefreshToken)) *RepositorioRefreshToken_Salvar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*auth.RefreshToken))
	})
	return _c
}

func (_c *RepositorioRefreshToken_Salvar_Call) Return(_a0 error) *RepositorioRefreshToken_Salvar_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RepositorioRefreshToken_Salvar_Call) RunAndReturn(run func(context.Context, *auth.RefreshToken) error) *RepositorioRefreshToken_Salvar_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepositorioRefreshToken creates a new instance of RepositorioRefreshToken. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositorioRefreshToken(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositorioRefreshToken {
	mock := &RepositorioRefreshToken{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
