// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UsuarioStatusRepository is an autogenerated mock type for the UsuarioStatusRepository type
type UsuarioStatusRepository struct {
	mock.Mock
}

type UsuarioStatusRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UsuarioStatusRepository) EXPECT() *UsuarioStatusRepository_Expecter {
	return &UsuarioStatusRepository_Expecter{mock: &_m.Mock}
}

// EstaAtivo provides a mock function with given fields: ctx, id
func (_m *UsuarioStatusRepository) EstaAtivo(ctx context.Context, id uint64) (bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for EstaAtivo")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) bool); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UsuarioStatusRepository_EstaAtivo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EstaAtivo'
type UsuarioStatusRepository_EstaAtivo_Call struct {
	*mock.Call
}

// EstaAtivo is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *UsuarioStatusRepository_Expecter) EstaAtivo(ctx interface{}, id interface{}) *UsuarioStatusRepository_EstaAtivo_Call {
	return &UsuarioStatusRepository_EstaAtivo_Call{Call: _e.mock.On("EstaAtivo", ctx, id)}
}

func (_c *UsuarioStatusRepository_EstaAtivo_Call) Run(run func(ctx context.Context, id uint64)) *UsuarioStatusRepository_EstaAtivo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *UsuarioStatusRepository_EstaAtivo_Call) Return(_a0 bool, _a1 error) *UsuarioStatusRepository_EstaAtivo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UsuarioStatusRepository_EstaAtivo_Call) RunAndReturn(run func(context.Context, uint64) (bool, error)) *UsuarioStatusRepository_EstaAtivo_Call {
	_c.Call.Return(run)
	return _c
}

// NewUsuarioStatusRepository creates a new instance of UsuarioStatusRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsuarioStatusRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UsuarioStatusRepository {
	mock := &UsuarioStatusRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
