// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	usuario "github.com/muriloperosa/soat-architecture/internal/domain/usuario"
	mock "github.com/stretchr/testify/mock"
)

// UsuarioRepository is an autogenerated mock type for the UsuarioRepository type
type UsuarioRepository struct {
	mock.Mock
}

type UsuarioRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UsuarioRepository) EXPECT() *UsuarioRepository_Expecter {
	return &UsuarioRepository_Expecter{mock: &_m.Mock}
}

// Atualizar provides a mock function with given fields: ctx, u
func (_m *UsuarioRepository) Atualizar(ctx context.Context, u *usuario.Usuario) error {
	ret := _m.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for Atualizar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *usuario.Usuario) error); ok {
		r0 = rf(ctx, u)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UsuarioRepository_Atualizar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Atualizar'
type UsuarioRepository_Atualizar_Call struct {
	*mock.Call
}

// Atualizar is a helper method to define mock.On call
//   - ctx context.Context
//   - u *usuario.Usuario
func (_e *UsuarioRepository_Expecter) Atualizar(ctx interface{}, u interface{}) *UsuarioRepository_Atualizar_Call {
	return &UsuarioRepository_Atualizar_Call{Call: _e.mock.On("Atualizar", ctx, u)}
}

func (_c *UsuarioRepository_Atualizar_Call) Run(run func(ctx context.Context, u *usuario.Usuario)) *UsuarioRepository_Atualizar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*usuario.Usuario))
	})
	return _c
}

func (_c *UsuarioRepository_Atualizar_Call) Return(_a0 error) *UsuarioRepository_Atualizar_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UsuarioRepository_Atualizar_Call) RunAndReturn(run func(context.Context, *usuario.Usuario) error) *UsuarioRepository_Atualizar_Call {
	_c.Call.Return(run)
	return _c
}

// BuscarPorEmail provides a mock function with given fields: ctx, email
func (_m *UsuarioRepository) BuscarPorEmail(ctx context.Context, email string) (*usuario.Usuario, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for BuscarPorEmail")
	}

	var r0 *usuario.Usuario
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*usuario.Usuario, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *usuario.Usuario); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usuario.Usuario)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UsuarioRepository_BuscarPorEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuscarPorEmail'
type UsuarioRepository_BuscarPorEmail_Call struct {
	*mock.Call
}

// BuscarPorEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *UsuarioRepository_Expecter) BuscarPorEmail(ctx interface{}, email interface{}) *UsuarioRepository_BuscarPorEmail_Call {
	return &UsuarioRepository_BuscarPorEmail_Call{Call: _e.mock.On("BuscarPorEmail", ctx, email)}
}

func (_c *UsuarioRepository_BuscarPorEmail_Call) Run(run func(ctx context.Context, email string)) *UsuarioRepository_BuscarPorEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UsuarioRepository_BuscarPorEmail_Call) Return(_a0 *usuario.Usuario, _a1 error) *UsuarioRepository_BuscarPorEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UsuarioRepository_BuscarPorEmail_Call) RunAndReturn(run func(context.Context, string) (*usuario.Usuario, error)) *UsuarioRepository_BuscarPorEmail_Call {
	_c.Call.Return(run)
	return _c
}

// BuscarPorID provides a mock function with given fields: ctx, id
func (_m *UsuarioRepository) BuscarPorID(ctx context.Context, id uint64) (*usuario.Usuario, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for BuscarPorID")
	}

	var r0 *usuario.Usuario
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (*usuario.Usuario, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) *usuario.Usuario); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usuario.Usuario)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UsuarioRepository_BuscarPorID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuscarPorID'
type UsuarioRepository_BuscarPorID_Call struct {
	*mock.Call
}

// BuscarPorID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *UsuarioRepository_Expecter) BuscarPorID(ctx interface{}, id interface{}) *UsuarioRepository_BuscarPorID_Call {
	return &UsuarioRepository_BuscarPorID_Call{Call: _e.mock.On("BuscarPorID", ctx, id)}
}

func (_c *UsuarioRepository_BuscarPorID_Call) Run(run func(ctx context.Context, id uint64)) *UsuarioRepository_BuscarPorID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *UsuarioRepository_BuscarPorID_Call) Return(_a0 *usuario.Usuario, _a1 error) *UsuarioRepository_BuscarPorID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UsuarioRepository_BuscarPorID_Call) RunAndReturn(run func(context.Context, uint64) (*usuario.Usuario, error)) *UsuarioRepository_BuscarPorID_Call {
	_c.Call.Return(run)
	return _c
}

// Salvar provides a mock function with given fields: ctx, u
func (_m *UsuarioRepository) Salvar(ctx context.Context, u *usuario.Usuario) error {
	ret := _m.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for Salvar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *usuario.Usuario) error); ok {
		r0 = rf(ctx, u)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UsuarioRepository_Salvar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Salvar'
type UsuarioRepository_Salvar_Call struct {
	*mock.Call
}

// Salvar is a helper method to define mock.On call
//   - ctx context.Context
//   - u *usuario.Usuario
func (_e *UsuarioRepository_Expecter) Salvar(ctx interface{}, u interface{}) *UsuarioRepository_Salvar_Call {
	return &UsuarioRepository_Salvar_Call{Call: _e.mock.On("Salvar", ctx, u)}
}

func (_c *UsuarioRepository_Salvar_Call) Run(run func(ctx context.Context, u *usuario.Usuario)) *UsuarioRepository_Salvar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*usuario.Usuario))
	})
	return _c
}

func (_c *UsuarioRepository_Salvar_Call) Return(_a0 error) *UsuarioRepository_Salvar_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UsuarioRepository_Salvar_Call) RunAndReturn(run func(context.Context, *usuario.Usuario) error) *UsuarioRepository_Salvar_Call {
	_c.Call.Return(run)
	return _c
}

// NewUsuarioRepository creates a new instance of UsuarioRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsuarioRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UsuarioRepository {
	mock := &UsuarioRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
