// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// EmailSender is an autogenerated mock type for the EmailSender type
type EmailSender struct {
	mock.Mock
}

type EmailSender_Expecter struct {
	mock *mock.Mock
}

func (_m *EmailSender) EXPECT() *EmailSender_Expecter {
	return &EmailSender_Expecter{mock: &_m.Mock}
}

// Enviar provides a mock function with given fields: ctx, destinatario, assunto, corpo
func (_m *EmailSender) Enviar(ctx context.Context, destinatario string, assunto string, corpo string) error {
	ret := _m.Called(ctx, destinatario, assunto, corpo)

	if len(ret) == 0 {
		panic("no return value specified for Enviar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, destinatario, assunto, corpo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EmailSender_Enviar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enviar'
type EmailSender_Enviar_Call struct {
	*mock.Call
}

// Enviar is a helper method to define mock.On call
//   - ctx context.Context
//   - destinatario string
//   - assunto string
//   - corpo string
func (_e *EmailSender_Expecter) Enviar(ctx interface{}, destinatario interface{}, assunto interface{}, corpo interface{}) *EmailSender_Enviar_Call {
	return &EmailSender_Enviar_Call{Call: _e.mock.On("Enviar", ctx, destinatario, assunto, corpo)}
}

func (_c *EmailSender_Enviar_Call) Run(run func(ctx context.Context, destinatario string, assunto string, corpo string)) *EmailSender_Enviar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *EmailSender_Enviar_Call) Return(_a0 error) *EmailSender_Enviar_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EmailSender_Enviar_Call) RunAndReturn(run func(context.Context, string, string, string) error) *EmailSender_Enviar_Call {
	_c.Call.Return(run)
	return _c
}

// NewEmailSender creates a new instance of EmailSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmailSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *EmailSender {
	mock := &EmailSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
