// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TransactionRunner is an autogenerated mock type for the TransactionRunner type
type TransactionRunner struct {
	mock.Mock
}

type TransactionRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *TransactionRunner) EXPECT() *TransactionRunner_Expecter {
	return &TransactionRunner_Expecter{mock: &_m.Mock}
}

// Executar provides a mock function with given fields: ctx, fn
func (_m *TransactionRunner) Executar(ctx context.Context, fn func(context.Context) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Executar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransactionRunner_Executar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Executar'
type TransactionRunner_Executar_Call struct {
	*mock.Call
}

// Executar is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(context.Context) error
func (_e *TransactionRunner_Expecter) Executar(ctx interface{}, fn interface{}) *TransactionRunner_Executar_Call {
	return &TransactionRunner_Executar_Call{Call: _e.mock.On("Executar", ctx, fn)}
}

func (_c *TransactionRunner_Executar_Call) Run(run func(ctx context.Context, fn func(context.Context) error)) *TransactionRunner_Executar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(context.Context) error))
	})
	return _c
}

func (_c *TransactionRunner_Executar_Call) Return(_a0 error) *TransactionRunner_Executar_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TransactionRunner_Executar_Call) RunAndReturn(run func(context.Context, func(context.Context) error) error) *TransactionRunner_Executar_Call {
	_c.Call.Return(run)
	return _c
}

// NewTransactionRunner creates a new instance of TransactionRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionRunner {
	mock := &TransactionRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
