// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	cliente "github.com/muriloperosa/soat-architecture/internal/domain/cliente"

	mock "github.com/stretchr/testify/mock"

	query "github.com/muriloperosa/soat-architecture/internal/domain/query"
)

// ClienteRepository is an autogenerated mock type for the ClienteRepository type
type ClienteRepository struct {
	mock.Mock
}

type ClienteRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ClienteRepository) EXPECT() *ClienteRepository_Expecter {
	return &ClienteRepository_Expecter{mock: &_m.Mock}
}

// Atualizar provides a mock function with given fields: ctx, _a1
func (_m *ClienteRepository) Atualizar(ctx context.Context, _a1 *cliente.Cliente) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Atualizar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *cliente.Cliente) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClienteRepository_Atualizar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Atualizar'
type ClienteRepository_Atualizar_Call struct {
	*mock.Call
}

// Atualizar is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *cliente.Cliente
func (_e *ClienteRepository_Expecter) Atualizar(ctx interface{}, _a1 interface{}) *ClienteRepository_Atualizar_Call {
	return &ClienteRepository_Atualizar_Call{Call: _e.mock.On("Atualizar", ctx, _a1)}
}

func (_c *ClienteRepository_Atualizar_Call) Run(run func(ctx context.Context, _a1 *cliente.Cliente)) *ClienteRepository_Atualizar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*cliente.Cliente))
	})
	return _c
}

func (_c *ClienteRepository_Atualizar_Call) Return(_a0 error) *ClienteRepository_Atualizar_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ClienteRepository_Atualizar_Call) RunAndReturn(run func(context.Context, *cliente.Cliente) error) *ClienteRepository_Atualizar_Call {
	_c.Call.Return(run)
	return _c
}

// BuscarPorDocumento provides a mock function with given fields: ctx, documento
func (_m *ClienteRepository) BuscarPorDocumento(ctx context.Context, documento string) (*cliente.Cliente, error) {
	ret := _m.Called(ctx, documento)

	if len(ret) == 0 {
		panic("no return value specified for BuscarPorDocumento")
	}

	var r0 *cliente.Cliente
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*cliente.Cliente, error)); ok {
		return rf(ctx, documento)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *cliente.Cliente); ok {
		r0 = rf(ctx, documento)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cliente.Cliente)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, documento)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClienteRepository_BuscarPorDocumento_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuscarPorDocumento'
type ClienteRepository_BuscarPorDocumento_Call struct {
	*mock.Call
}

// BuscarPorDocumento is a helper method to define mock.On call
//   - ctx context.Context
//   - documento string
func (_e *ClienteRepository_Expecter) BuscarPorDocumento(ctx interface{}, documento interface{}) *ClienteRepository_BuscarPorDocumento_Call {
	return &ClienteRepository_BuscarPorDocumento_Call{Call: _e.mock.On("BuscarPorDocumento", ctx, documento)}
}

func (_c *ClienteRepository_BuscarPorDocumento_Call) Run(run func(ctx context.Context, documento string)) *ClienteRepository_BuscarPorDocumento_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ClienteRepository_BuscarPorDocumento_Call) Return(_a0 *cliente.Cliente, _a1 error) *ClienteRepository_BuscarPorDocumento_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClienteRepository_BuscarPorDocumento_Call) RunAndReturn(run func(context.Context, string) (*cliente.Cliente, error)) *ClienteRepository_BuscarPorDocumento_Call {
	_c.Call.Return(run)
	return _c
}

// BuscarPorEmail provides a mock function with given fields: ctx, email
func (_m *ClienteRepository) BuscarPorEmail(ctx context.Context, email string) (*cliente.Cliente, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for BuscarPorEmail")
	}

	var r0 *cliente.Cliente
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*cliente.Cliente, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *cliente.Cliente); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cliente.Cliente)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClienteRepository_BuscarPorEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuscarPorEmail'
type ClienteRepository_BuscarPorEmail_Call struct {
	*mock.Call
}

// BuscarPorEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *ClienteRepository_Expecter) BuscarPorEmail(ctx interface{}, email interface{}) *ClienteRepository_BuscarPorEmail_Call {
	return &ClienteRepository_BuscarPorEmail_Call{Call: _e.mock.On("BuscarPorEmail", ctx, email)}
}

func (_c *ClienteRepository_BuscarPorEmail_Call) Run(run func(ctx context.Context, email string)) *ClienteRepository_BuscarPorEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ClienteRepository_BuscarPorEmail_Call) Return(_a0 *cliente.Cliente, _a1 error) *ClienteRepository_BuscarPorEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClienteRepository_BuscarPorEmail_Call) RunAndReturn(run func(context.Context, string) (*cliente.Cliente, error)) *ClienteRepository_BuscarPorEmail_Call {
	_c.Call.Return(run)
	return _c
}

// BuscarPorID provides a mock function with given fields: ctx, id
func (_m *ClienteRepository) BuscarPorID(ctx context.Context, id uint64) (*cliente.Cliente, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for BuscarPorID")
	}

	var r0 *cliente.Cliente
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (*cliente.Cliente, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) *cliente.Cliente); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cliente.Cliente)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClienteRepository_BuscarPorID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuscarPorID'
type ClienteRepository_BuscarPorID_Call struct {
	*mock.Call
}

// BuscarPorID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *ClienteRepository_Expecter) BuscarPorID(ctx interface{}, id interface{}) *ClienteRepository_BuscarPorID_Call {
	return &ClienteRepository_BuscarPorID_Call{Call: _e.mock.On("BuscarPorID", ctx, id)}
}

func (_c *ClienteRepository_BuscarPorID_Call) Run(run func(ctx context.Context, id uint64)) *ClienteRepository_BuscarPorID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *ClienteRepository_BuscarPorID_Call) Return(_a0 *cliente.Cliente, _a1 error) *ClienteRepository_BuscarPorID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClienteRepository_BuscarPorID_Call) RunAndReturn(run func(context.Context, uint64) (*cliente.Cliente, error)) *ClienteRepository_BuscarPorID_Call {
	_c.Call.Return(run)
	return _c
}

// Listar provides a mock function with given fields: ctx, params
func (_m *ClienteRepository) Listar(ctx context.Context, params query.Params) (query.Page[*cliente.Cliente], error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Listar")
	}

	var r0 query.Page[*cliente.Cliente]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, query.Params) (query.Page[*cliente.Cliente], error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, query.Params) query.Page[*cliente.Cliente]); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(query.Page[*cliente.Cliente])
	}

	if rf, ok := ret.Get(1).(func(context.Context, query.Params) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClienteRepository_Listar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Listar'
type ClienteRepository_Listar_Call struct {
	*mock.Call
}

// Listar is a helper method to define mock.On call
//   - ctx context.Context
//   - params query.Params
func (_e *ClienteRepository_Expecter) Listar(ctx interface{}, params interface{}) *ClienteRepository_Listar_Call {
	return &ClienteRepository_Listar_Call{Call: _e.mock.On("Listar", ctx, params)}
}

func (_c *ClienteRepository_Listar_Call) Run(run func(ctx context.Context, params query.Params)) *ClienteRepository_Listar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(query.Params))
	})
	return _c
}

func (_c *ClienteRepository_Listar_Call) Return(_a0 query.Page[*cliente.Cliente], _a1 error) *ClienteRepository_Listar_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClienteRepository_Listar_Call) RunAndReturn(run func(context.Context, query.Params) (query.Page[*cliente.Cliente], error)) *ClienteRepository_Listar_Call {
	_c.Call.Return(run)
	return _c
}

// Salvar provides a mock function with given fields: ctx, _a1
func (_m *ClienteRepository) Salvar(ctx context.Context, _a1 *cliente.Cliente) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Salvar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *cliente.Cliente) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClienteRepository_Salvar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Salvar'
type ClienteRepository_Salvar_Call struct {
	*mock.Call
}

// Salvar is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *cliente.Cliente
func (_e *ClienteRepository_Expecter) Salvar(ctx interface{}, _a1 interface{}) *ClienteRepository_Salvar_Call {
	return &ClienteRepository_Salvar_Call{Call: _e.mock.On("Salvar", ctx, _a1)}
}

func (_c *ClienteRepository_Salvar_Call) Run(run func(ctx context.Context, _a1 *cliente.Cliente)) *ClienteRepository_Salvar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*cliente.Cliente))
	})
	return _c
}

func (_c *ClienteRepository_Salvar_Call) Return(_a0 error) *ClienteRepository_Salvar_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ClienteRepository_Salvar_Call) RunAndReturn(run func(context.Context, *cliente.Cliente) error) *ClienteRepository_Salvar_Call {
	_c.Call.Return(run)
	return _c
}

// NewClienteRepository creates a new instance of ClienteRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClienteRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClienteRepository {
	mock := &ClienteRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
