// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	orcamento "github.com/muriloperosa/soat-architecture/internal/domain/orcamento"
	mock "github.com/stretchr/testify/mock"
)

// OrcamentoRepository is an autogenerated mock type for the OrcamentoRepository type
type OrcamentoRepository struct {
	mock.Mock
}

type OrcamentoRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *OrcamentoRepository) EXPECT() *OrcamentoRepository_Expecter {
	return &OrcamentoRepository_Expecter{mock: &_m.Mock}
}

// Atualizar provides a mock function with given fields: ctx, _a1
func (_m *OrcamentoRepository) Atualizar(ctx context.Context, _a1 *orcamento.Orcamento) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Atualizar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *orcamento.Orcamento) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrcamentoRepository_Atualizar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Atualizar'
type OrcamentoRepository_Atualizar_Call struct {
	*mock.Call
}

// Atualizar is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *orcamento.Orcamento
func (_e *OrcamentoRepository_Expecter) Atualizar(ctx interface{}, _a1 interface{}) *OrcamentoRepository_Atualizar_Call {
	return &OrcamentoRepository_Atualizar_Call{Call: _e.mock.On("Atualizar", ctx, _a1)}
}

func (_c *OrcamentoRepository_Atualizar_Call) Run(run func(ctx context.Context, _a1 *orcamento.Orcamento)) *OrcamentoRepository_Atualizar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*orcamento.Orcamento))
	})
	return _c
}

func (_c *OrcamentoRepository_Atualizar_Call) Return(_a0 error) *OrcamentoRepository_Atualizar_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrcamentoRepository_Atualizar_Call) RunAndReturn(run func(context.Context, *orcamento.Orcamento) error) *OrcamentoRepository_Atualizar_Call {
	_c.Call.Return(run)
	return _c
}

// BuscarPorOrdemServicoID provides a mock function with given fields: ctx, ordemServicoID
func (_m *OrcamentoRepository) BuscarPorOrdemServicoID(ctx context.Context, ordemServicoID uint64) (*orcamento.Orcamento, error) {
	ret := _m.Called(ctx, ordemServicoID)

	if len(ret) == 0 {
		panic("no return value specified for BuscarPorOrdemServicoID")
	}

	var r0 *orcamento.Orcamento
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (*orcamento.Orcamento, error)); ok {
		return rf(ctx, ordemServicoID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) *orcamento.Orcamento); ok {
		r0 = rf(ctx, ordemServicoID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*orcamento.Orcamento)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, ordemServicoID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrcamentoRepository_BuscarPorOrdemServicoID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuscarPorOrdemServicoID'
type OrcamentoRepository_BuscarPorOrdemServicoID_Call struct {
	*mock.Call
}

// BuscarPorOrdemServicoID is a helper method to define mock.On call
//   - ctx context.Context
//   - ordemServicoID uint64
func (_e *OrcamentoRepository_Expecter) BuscarPorOrdemServicoID(ctx interface{}, ordemServicoID interface{}) *OrcamentoRepository_BuscarPorOrdemServicoID_Call {
	return &OrcamentoRepository_BuscarPorOrdemServicoID_Call{Call: _e.mock.On("BuscarPorOrdemServicoID", ctx, ordemServicoID)}
}

func (_c *OrcamentoRepository_BuscarPorOrdemServicoID_Call) Run(run func(ctx context.Context, ordemServicoID uint64)) *OrcamentoRepository_BuscarPorOrdemServicoID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *OrcamentoRepository_BuscarPorOrdemServicoID_Call) Return(_a0 *orcamento.Orcamento, _a1 error) *OrcamentoRepository_BuscarPorOrdemServicoID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrcamentoRepository_BuscarPorOrdemServicoID_Call) RunAndReturn(run func(context.Context, uint64) (*orcamento.Orcamento, error)) *OrcamentoRepository_BuscarPorOrdemServicoID_Call {
	_c.Call.Return(run)
	return _c
}

// BuscarPorOrdensServicoIDs provides a mock function with given fields: ctx, ordensServicoIDs
func (_m *OrcamentoRepository) BuscarPorOrdensServicoIDs(ctx context.Context, ordensServicoIDs []uint64) ([]*orcamento.Orcamento, error) {
	ret := _m.Called(ctx, ordensServicoIDs)

	if len(ret) == 0 {
		panic("no return value specified for BuscarPorOrdensServicoIDs")
	}

	var r0 []*orcamento.Orcamento
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint64) ([]*orcamento.Orcamento, error)); ok {
		return rf(ctx, ordensServicoIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uint64) []*orcamento.Orcamento); ok {
		r0 = rf(ctx, ordensServicoIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*orcamento.Orcamento)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uint64) error); ok {
		r1 = rf(ctx, ordensServicoIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrcamentoRepository_BuscarPorOrdensServicoIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuscarPorOrdensServicoIDs'
type OrcamentoRepository_BuscarPorOrdensServicoIDs_Call struct {
	*mock.Call
}

// BuscarPorOrdensServicoIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ordensServicoIDs []uint64
func (_e *OrcamentoRepository_Expecter) BuscarPorOrdensServicoIDs(ctx interface{}, ordensServicoIDs interface{}) *OrcamentoRepository_BuscarPorOrdensServicoIDs_Call {
	return &OrcamentoRepository_BuscarPorOrdensServicoIDs_Call{Call: _e.mock.On("BuscarPorOrdensServicoIDs", ctx, ordensServicoIDs)}
}

func (_c *OrcamentoRepository_BuscarPorOrdensServicoIDs_Call) Run(run func(ctx context.Context, ordensServicoIDs []uint64)) *OrcamentoRepository_BuscarPorOrdensServicoIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uint64))
	})
	return _c
}

func (_c *OrcamentoRepository_BuscarPorOrdensServicoIDs_Call) Return(_a0 []*orcamento.Orcamento, _a1 error) *OrcamentoRepository_BuscarPorOrdensServicoIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrcamentoRepository_BuscarPorOrdensServicoIDs_Call) RunAndReturn(run func(context.Context, []uint64) ([]*orcamento.Orcamento, error)) *OrcamentoRepository_BuscarPorOrdensServicoIDs_Call {
	_c.Call.Return(run)
	return _c
}

// Salvar provides a mock function with given fields: ctx, _a1
func (_m *OrcamentoRepository) Salvar(ctx context.Context, _a1 *orcamento.Orcamento) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Salvar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *orcamento.Orcamento) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrcamentoRepository_Salvar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Salvar'
type OrcamentoRepository_Salvar_Call struct {
	*mock.Call
}

// Salvar is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *orcamento.Orcamento
func (_e *OrcamentoRepository_Expecter) Salvar(ctx interface{}, _a1 interface{}) *OrcamentoRepository_Salvar_Call {
	return &OrcamentoRepository_Salvar_Call{Call: _e.mock.On("Salvar", ctx, _a1)}
}

func (_c *OrcamentoRepository_Salvar_Call) Run(run func(ctx context.Context, _a1 *orcamento.Orcamento)) *OrcamentoRepository_Salvar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*orcamento.Orcamento))
	})
	return _c
}

func (_c *OrcamentoRepository_Salvar_Call) Return(_a0 error) *OrcamentoRepository_Salvar_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrcamentoRepository_Salvar_Call) RunAndReturn(run func(context.Context, *orcamento.Orcamento) error) *OrcamentoRepository_Salvar_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrcamentoRepository creates a new instance of OrcamentoRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrcamentoRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrcamentoRepository {
	mock := &OrcamentoRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
