// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	peca "github.com/muriloperosa/soat-architecture/internal/domain/peca"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// Atualizar provides a mock function with given fields: ctx, _a1
func (_m *Repository) Atualizar(ctx context.Context, _a1 *peca.Peca) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Atualizar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *peca.Peca) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_Atualizar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Atualizar'
type Repository_Atualizar_Call struct {
	*mock.Call
}

// Atualizar is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *peca.Peca
func (_e *Repository_Expecter) Atualizar(ctx interface{}, _a1 interface{}) *Repository_Atualizar_Call {
	return &Repository_Atualizar_Call{Call: _e.mock.On("Atualizar", ctx, _a1)}
}

func (_c *Repository_Atualizar_Call) Run(run func(ctx context.Context, _a1 *peca.Peca)) *Repository_Atualizar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*peca.Peca))
	})
	return _c
}

func (_c *Repository_Atualizar_Call) Return(_a0 error) *Repository_Atualizar_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_Atualizar_Call) RunAndReturn(run func(context.Context, *peca.Peca) error) *Repository_Atualizar_Call {
	_c.Call.Return(run)
	return _c
}

// BuscarPorCodigo provides a mock function with given fields: ctx, codigo
func (_m *Repository) BuscarPorCodigo(ctx context.Context, codigo string) (*peca.Peca, error) {
	ret := _m.Called(ctx, codigo)

	if len(ret) == 0 {
		panic("no return value specified for BuscarPorCodigo")
	}

	var r0 *peca.Peca
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*peca.Peca, error)); ok {
		return rf(ctx, codigo)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *peca.Peca); ok {
		r0 = rf(ctx, codigo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*peca.Peca)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, codigo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_BuscarPorCodigo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuscarPorCodigo'
type Repository_BuscarPorCodigo_Call struct {
	*mock.Call
}

// BuscarPorCodigo is a helper method to define mock.On call
//   - ctx context.Context
//   - codigo string
func (_e *Repository_Expecter) BuscarPorCodigo(ctx interface{}, codigo interface{}) *Repository_BuscarPorCodigo_Call {
	return &Repository_BuscarPorCodigo_Call{Call: _e.mock.On("BuscarPorCodigo", ctx, codigo)}
}

func (_c *Repository_BuscarPorCodigo_Call) Run(run func(ctx context.Context, codigo string)) *Repository_BuscarPorCodigo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_BuscarPorCodigo_Call) Return(_a0 *peca.Peca, _a1 error) *Repository_BuscarPorCodigo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_BuscarPorCodigo_Call) RunAndReturn(run func(context.Context, string) (*peca.Peca, error)) *Repository_BuscarPorCodigo_Call {
	_c.Call.Return(run)
	return _c
}

// BuscarPorID provides a mock function with given fields: ctx, id
func (_m *Repository) BuscarPorID(ctx context.Context, id uint64) (*peca.Peca, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for BuscarPorID")
	}

	var r0 *peca.Peca
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (*peca.Peca, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) *peca.Peca); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*peca.Peca)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_BuscarPorID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuscarPorID'
type Repository_BuscarPorID_Call struct {
	*mock.Call
}

// BuscarPorID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *Repository_Expecter) BuscarPorID(ctx interface{}, id interface{}) *Repository_BuscarPorID_Call {
	return &Repository_BuscarPorID_Call{Call: _e.mock.On("BuscarPorID", ctx, id)}
}

func (_c *Repository_BuscarPorID_Call) Run(run func(ctx context.Context, id uint64)) *Repository_BuscarPorID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *Repository_BuscarPorID_Call) Return(_a0 *peca.Peca, _a1 error) *Repository_BuscarPorID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_BuscarPorID_Call) RunAndReturn(run func(context.Context, uint64) (*peca.Peca, error)) *Repository_BuscarPorID_Call {
	_c.Call.Return(run)
	return _c
}

// BuscarPorIDComBloqueio provides a mock function with given fields: ctx, id
func (_m *Repository) BuscarPorIDComBloqueio(ctx context.Context, id uint64) (*peca.Peca, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for BuscarPorIDComBloqueio")
	}

	var r0 *peca.Peca
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (*peca.Peca, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) *peca.Peca); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*peca.Peca)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_BuscarPorIDComBloqueio_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuscarPorIDComBloqueio'
type Repository_BuscarPorIDComBloqueio_Call struct {
	*mock.Call
}

// BuscarPorIDComBloqueio is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *Repository_Expecter) BuscarPorIDComBloqueio(ctx interface{}, id interface{}) *Repository_BuscarPorIDComBloqueio_Call {
	return &Repository_BuscarPorIDComBloqueio_Call{Call: _e.mock.On("BuscarPorIDComBloqueio", ctx, id)}
}

func (_c *Repository_BuscarPorIDComBloqueio_Call) Run(run func(ctx context.Context, id uint64)) *Repository_BuscarPorIDComBloqueio_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *Repository_BuscarPorIDComBloqueio_Call) Return(_a0 *peca.Peca, _a1 error) *Repository_BuscarPorIDComBloqueio_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_BuscarPorIDComBloqueio_Call) RunAndReturn(run func(context.Context, uint64) (*peca.Peca, error)) *Repository_BuscarPorIDComBloqueio_Call {
	_c.Call.Return(run)
	return _c
}

// Salvar provides a mock function with given fields: ctx, _a1
func (_m *Repository) Salvar(ctx context.Context, _a1 *peca.Peca) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Salvar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *peca.Peca) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_Salvar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Salvar'
type Repository_Salvar_Call struct {
	*mock.Call
}

// Salvar is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *peca.Peca
func (_e *Repository_Expecter) Salvar(ctx interface{}, _a1 interface{}) *Repository_Salvar_Call {
	return &Repository_Salvar_Call{Call: _e.mock.On("Salvar", ctx, _a1)}
}

func (_c *Repository_Salvar_Call) Run(run func(ctx context.Context, _a1 *peca.Peca)) *Repository_Salvar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*peca.Peca))
	})
	return _c
}

func (_c *Repository_Salvar_Call) Return(_a0 error) *Repository_Salvar_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_Salvar_Call) RunAndReturn(run func(context.Context, *peca.Peca) error) *Repository_Salvar_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
